---
## 1. 경로 / 설정

In [1]:
from pathlib import Path
import os, json
from dotenv import load_dotenv

# 프로젝트 루트 기준 (notebook이 notebooks/ 안에 있다고 가정)
PROJECT_ROOT = Path.cwd().parent
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
DATA_EVAL = PROJECT_ROOT / "data" / "eval"
VECTOR_DIR = PROJECT_ROOT / "data" / "vector_store" / "week3_chroma"

for p in [DATA_PROCESSED, DATA_EVAL, VECTOR_DIR]:
    p.mkdir(parents=True, exist_ok=True)

# .env 로드 (프로젝트 루트 + 작업 디렉토리 둘 다 시도)
load_dotenv(PROJECT_ROOT / ".env")
load_dotenv()
assert os.environ.get("OPENAI_API_KEY"), "OPENAI_API_KEY가 .env에 없거나 로드 안 됨"
assert os.environ.get(
    "ANTHROPIC_API_KEY"
), "ANTHROPIC_API_KEY가 .env에 없거나 로드 안 됨"

# Hyperparams
CHUNK_SIZE = 512
CHUNK_OVERLAP = 100
EMBEDDING_MODEL = "intfloat/multilingual-e5-base"
GEN_MODEL = "gpt-4o-mini"  # 답변 생성: OpenAI
JUDGE_MODEL = "claude-haiku-4-5"  # RAGAS 채점: Anthropic (생성과 다른 계열로 분리)
# 모델명이 안 맞으면 1-b 셀에서 에러가 나니 콘솔의 현재 모델명으로 교체
TOP_K = 5
COLLECTION_NAME = "breast_rag_week3"  # 기존 인덱스 재사용을 위해 그대로 유지

print("PROJECT_ROOT:", PROJECT_ROOT)
print("OPENAI key:", "OK" if os.environ.get("OPENAI_API_KEY") else "MISSING")
print("ANTHROPIC key:", "OK" if os.environ.get("ANTHROPIC_API_KEY") else "MISSING")
print("PDF 폴더 확인:")
for src in (DATA_RAW / "pdf").iterdir() if (DATA_RAW / "pdf").exists() else []:
    pdfs = list(src.glob("*.pdf"))
    print(f"  {src.name}: {len(pdfs)}개")

PROJECT_ROOT: /Users/jian/Documents/rag-agent-portfolio
OPENAI key: OK
ANTHROPIC key: OK
PDF 폴더 확인:
  esmo: 1개
  ncc: 3개
  kbcs: 1개
  nccn: 5개

---
## 1-b. API 연결 확인 (생성=OpenAI, 채점=Anthropic)

본격 실행 전에 두 API가 실제로 응답하는지 1콜씩 확인한다.
모델명이 틀리거나 키가 없으면 여기서 바로 에러가 나므로, RAGAS가 조용히 NaN을 내는 상황을 예방한다.

In [2]:
from langchain_openai import ChatOpenAI
from langchain_anthropic import ChatAnthropic

_gen_test = ChatOpenAI(model=GEN_MODEL, temperature=0).invoke(
    "한국어로 'ok'라고만 답해."
)
print("OpenAI(", GEN_MODEL, ") ->", _gen_test.content)

_judge_test = ChatAnthropic(model=JUDGE_MODEL, temperature=0).invoke(
    "한국어로 'ok'라고만 답해."
)
print("Anthropic(", JUDGE_MODEL, ") ->", _judge_test.content)

OpenAI( gpt-4o-mini ) -> ok
Anthropic( claude-haiku-4-5 ) -> ok

---
## 2. PDF 로드 (PyMuPDF)

`manifest.json`이 있으면 메타데이터를 chunk에 그대로 붙인다. 없으면 폴더명을 출처로 사용.

In [3]:
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_core.documents import Document

# manifest 로드 (다운로드 스크립트가 만들어둔 파일)
manifest_path = DATA_RAW / "metadata" / "manifest.json"
if manifest_path.exists():
    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)
    meta_lookup = {m["filename"]: m for m in manifest if m.get("downloaded")}
    print(f"manifest 로드 완료: {len(meta_lookup)}개 항목")
else:
    meta_lookup = {}
    print("manifest.json 없음 - 폴더명만 메타데이터로 사용")


def load_all_pdfs(pdf_root: Path) -> list[Document]:
    """data/raw/pdf/**/*.pdf 전부 로드하고 메타데이터 부착. (baseline: PyMuPDFLoader)"""
    all_docs = []
    for pdf_path in pdf_root.rglob("*.pdf"):
        try:
            loader = PyMuPDFLoader(str(pdf_path))
            docs = loader.load()
            extra = meta_lookup.get(pdf_path.name, {})
            for d in docs:
                d.metadata.update(
                    {
                        "filename": pdf_path.name,
                        "source_folder": pdf_path.parent.name,
                        "org": extra.get("org", pdf_path.parent.name),
                        "title": extra.get("title", pdf_path.stem),
                        "language": extra.get("language", "unknown"),
                        "doc_type": extra.get("doc_type", "unknown"),
                        "priority": extra.get("priority", "unknown"),
                    }
                )
            all_docs.extend(docs)
            print(f"  OK   {pdf_path.name}: {len(docs)} pages")
        except Exception as e:
            print(f"  FAIL {pdf_path.name}: {e}")
    return all_docs


documents = load_all_pdfs(DATA_RAW / "pdf")
print(f"\n총 페이지 수: {len(documents)}")

manifest 로드 완료: 13개 항목
  OK   esmo_breast_cancer_patient_guide_korean.pdf: 70 pages
  OK   ncc_breast_cancer_prevention_guide.pdf: 10 pages
  OK   ncc_breast_cancer_screening_guideline_2015.pdf: 114 pages
  OK   ncc_breast_cancer_hormone_therapy.pdf: 2 pages
  OK   kbcs_korean_breast_cancer_guideline_2023.pdf: 270 pages
  OK   nccn_dcis_patient.pdf: 52 pages
  OK   nccn_breast_cancer_screening_diagnosis_patient.pdf: 52 pages
  OK   nccn_invasive_breast_cancer_patient.pdf: 86 pages
  OK   nccn_metastatic_breast_cancer_patient.pdf: 66 pages
  OK   nccn_inflammatory_breast_cancer_patient.pdf: 74 pages

총 페이지 수: 796

### 데이터 sanity check

첫 페이지 1개만 출력해서 PDF가 제대로 파싱됐는지 확인.

In [4]:
if documents:
    print("--- 첫 페이지 메타데이터 ---")
    print(json.dumps(documents[0].metadata, ensure_ascii=False, indent=2))
    print("\n--- 첫 페이지 본문 (앞 500자) ---")
    print(documents[0].page_content[:500])

--- 첫 페이지 메타데이터 ---
{
  "producer": "Adobe PDF Library 15.0",
  "creator": "Adobe InDesign 16.1 (Macintosh)",
  "creationdate": "2021-04-22T10:54:24+01:00",
  "source": "/Users/jian/Documents/rag-agent-portfolio/data/raw/pdf/esmo/esmo_breast_cancer_patient_guide_korean.pdf",
  "file_path": "/Users/jian/Documents/rag-agent-portfolio/data/raw/pdf/esmo/esmo_breast_cancer_patient_guide_korean.pdf",
  "total_pages": 70,
  "format": "PDF 1.6",
  "title": "ESMO Breast Cancer Guide for Patients (Korean)",
  "author": "European Society for Medical Oncology",
  "subject": "ESMO",
  "keywords": "European Society for Medical Oncology, ESMO, KO, Breast, Cancer, Guide, Patients, Korean",
  "moddate": "2021-05-01T18:37:20+02:00",
  "trapped": "",
  "modDate": "D:20210501183720+02'00'",
  "creationDate": "D:20210422105424+01'00'",
  "page": 0,
  "filename": "esmo_breast_cancer_patient_guide_korean.pdf",
  "source_folder": "esmo",
  "org": "ESMO",
  "language": "ko",
  "doc_type": "patient_guideline",
  "priority": "P1"
}

--- 첫 페이지 본문 (앞 500자) ---
esmo.org
ESMO 환자 안내서 시리즈
ESMO 임상 진료 지침에 기초함
유방암이란?
여러분의 질문에
답변해 드리겠습니다
유방암

---
## 3. Chunking (RecursiveCharacterTextSplitter)

In [5]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=["\n\n", "\n", ". ", " ", ""],
    length_function=len,
)

chunks = splitter.split_documents(documents)
print(f"전체 chunk 수: {len(chunks)}")
print(
    f"평균 chunk 길이(문자): {sum(len(c.page_content) for c in chunks) / max(len(chunks),1):.0f}"
)
print("\n--- chunk 예시 ---")
print(chunks[0].metadata)
print(chunks[0].page_content[:300])

전체 chunk 수: 3214
평균 chunk 길이(문자): 436

--- chunk 예시 ---
{'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign 16.1 (Macintosh)', 'creationdate': '2021-04-22T10:54:24+01:00', 'source': '/Users/jian/Documents/rag-agent-portfolio/data/raw/pdf/esmo/esmo_breast_cancer_patient_guide_korean.pdf', 'file_path': '/Users/jian/Documents/rag-agent-portfolio/data/raw/pdf/esmo/esmo_breast_cancer_patient_guide_korean.pdf', 'total_pages': 70, 'format': 'PDF 1.6', 'title': 'ESMO Breast Cancer Guide for Patients (Korean)', 'author': 'European Society for Medical Oncology', 'subject': 'ESMO', 'keywords': 'European Society for Medical Oncology, ESMO, KO, Breast, Cancer, Guide, Patients, Korean', 'moddate': '2021-05-01T18:37:20+02:00', 'trapped': '', 'modDate': "D:20210501183720+02'00'", 'creationDate': "D:20210422105424+01'00'", 'page': 0, 'filename': 'esmo_breast_cancer_patient_guide_korean.pdf', 'source_folder': 'esmo', 'org': 'ESMO', 'language': 'ko', 'doc_type': 'patient_guideline', 'priority': 'P1'}
esmo.org
ESMO 환자 안내서 시리즈
ESMO 임상 진료 지침에 기초함
유방암이란?
여러분의 질문에
답변해 드리겠습니다
유방암

---
## 4. Embedding + Chroma 인덱싱

e5-base는 처음 한 번만 다운로드(~500MB)된다. **Jupyter 셀에서 다운로드가 멈춘 듯 보이면**, 터미널에서 미리 받아두는 게 안정적이다(진행상황이 보임):

```bash
python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('intfloat/multilingual-e5-base')"
```

아래 셀은 모델이 캐시에 있으면 자동으로 오프라인 로드(네트워크 확인 hang 방지)하고, 없으면 다운로드한다.
e5 계열은 `passage: ...`, `query: ...` prefix 규칙이 있는데 baseline에서는 default로 두고 4주차 이후 비교.

In [6]:
import os
from pathlib import Path
from huggingface_hub import snapshot_download

# 이전 실행에서 강제로 켜진 오프라인 모드 해제
os.environ.pop("HF_HUB_OFFLINE", None)
os.environ.pop("TRANSFORMERS_OFFLINE", None)

# 네트워크 체크가 오래 걸리는 것 방지
os.environ["HF_HUB_ETAG_TIMEOUT"] = "10"
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "120"
os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"

print("embedding model:", EMBEDDING_MODEL)

# 1단계: 로컬 캐시에 모델 전체 snapshot이 있는지 확인
try:
    model_dir = snapshot_download(
        repo_id=EMBEDDING_MODEL,
        local_files_only=True,
    )
    print("로컬 캐시에서 모델 snapshot 확인:", model_dir)

except Exception as e:
    print("로컬 캐시가 없거나 불완전합니다.")
    print("다운로드를 진행합니다.")
    print("cache error:", repr(e))

    model_dir = snapshot_download(
        repo_id=EMBEDDING_MODEL,
        local_files_only=False,
        max_workers=1,
    )
    print("모델 다운로드 완료:", model_dir)


# 2단계: 실제 로컬 경로에서 embedding 모델 로드
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

embeddings = HuggingFaceEmbeddings(
    model_name=model_dir,  # repo_id가 아니라 실제 로컬 snapshot 경로 사용
    model_kwargs={"device": "cpu"},
    encode_kwargs={
        "normalize_embeddings": True,
        "batch_size": 16,
    },
)

# 3단계: 실제 embedding이 되는지 테스트
test_vec = embeddings.embed_query("유방암 치료 가이드라인 테스트")
print("embedding 모델 로드 완료")
print("test embedding dim:", len(test_vec))

embedding model: intfloat/multilingual-e5-base
로컬 캐시에서 모델 snapshot 확인: /Users/jian/.cache/huggingface/hub/models--intfloat--multilingual-e5-base/snapshots/d128750597153bb5987e10b1c3493a34e5a4502a
embedding 모델 로드 완료
test embedding dim: 768

In [7]:
# 기존 인덱스가 있으면 그대로 사용, 없으면 새로 생성
import chromadb

client = chromadb.PersistentClient(path=str(VECTOR_DIR))
existing = [c.name for c in client.list_collections()]
print("기존 컬렉션:", existing)

if COLLECTION_NAME in existing:
    vectorstore = Chroma(
        collection_name=COLLECTION_NAME,
        embedding_function=embeddings,
        persist_directory=str(VECTOR_DIR),
    )
    print(f"기존 컬렉션 로드: {vectorstore._collection.count()}개 chunk")
else:
    print(f"새 컬렉션 생성 중... ({len(chunks)}개 chunk 인덱싱)")
    vectorstore = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        collection_name=COLLECTION_NAME,
        persist_directory=str(VECTOR_DIR),
    )
    print(f"인덱싱 완료: {vectorstore._collection.count()}개")

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

기존 컬렉션: []
새 컬렉션 생성 중... (3214개 chunk 인덱싱)
인덱싱 완료: 3214개

### 검색 sanity check

In [8]:
retriever = vectorstore.as_retriever(search_kwargs={"k": TOP_K})

test_q = "유방암 검진은 몇 살부터 받아야 하나요?"
hits = retriever.invoke(test_q)
print(f"질문: {test_q}")
print(f"검색 결과 {len(hits)}개\n")
for i, h in enumerate(hits, 1):
    print(
        f"[{i}] {h.metadata.get('org')} / p.{h.metadata.get('page','?')} / {h.metadata.get('filename')}"
    )
    print("   ", h.page_content[:150].replace("\n", " "), "...\n")

Failed to send telemetry event CollectionQueryEvent: capture() takes 1 positional argument but 3 were given

질문: 유방암 검진은 몇 살부터 받아야 하나요?
검색 결과 5개

[1] 국립암센터 / p.8 / ncc_breast_cancer_prevention_guide.pdf
    ▶ 다섯!  내게 맞는 유방암 검진 프로그램은? 유방암 검진이란 증상이 없는 상태에서 유방촬영술 등을 통하여 유방암을 조기에  발견하는 것입니다. 현재 국가암검진 프로그램에서는 40세 이상의 여성을 대상으로  2년을 주기로 유방촬영검사를 기본 검사로 실시하고 있습니다. ...

[2] 대한유방암학회 / p.184 / kbcs_korean_breast_cancer_guideline_2023.pdf
    2023 The 10 th Korean Clinical Practice Guideline for Breast Cancer | 185 제2장 조기 유방암 제3장 재발 및 전이성 유방암 제4장 유전성 유방암  제1장 비침습 유방암 하다[85] (LE 3, GR A).  누 ...

[3] 국립암센터 / p.8 / ncc_breast_cancer_prevention_guide.pdf
    국민 암예방 수칙 실천지침 _ 유방암 14 15   2년마다 유방촬영검사 ▶ 넷!  유방암 고위험군이라면? 유방에 만져지는 혹이 있거나, 유두 분비물 등의 증상이 있는 여성은 검진의 대상이 아니라 진료의 대상 으로서 임상유방진찰 등의 추가적인 조치가 필요합니다. 또한 ...

[4] 대한유방암학회 / p.211 / kbcs_korean_breast_cancer_guideline_2023.pdf
    신장암 검진을 위해 만 40세부터 신장 초음파 검사를 시작하고, 매 1-2년마다 검사하도록 고려할 수 있다. 보인자 로 진단 받은 소아에서 진단 시 정신운동(psychomotor) 평가, 증상이 있다면 뇌 MRI 검사를 고려할 수 있다. 악 성흑색종의 위험성을 고려하여 ...

[5] 국립암센터 / p.13 / ncc_breast_cancer_screening_guideline_2015.pdf
    10 유방암 검진 권고안 유방암 검진 권고안의 개발범위(PIPOH)는 다음과 같이 설정하였다(표 5).  P (Population) : 성인 (만 30세 이상), 고위험군 배제   I (Intervention) : 유방촬영술, 유방촬영술+유방초음파검사, 유방촬영술+ ...

---
## 5. LLM 답변 생성 (OpenAI gpt-4o-mini)

RAG 프롬프트 설계 포인트:
- context 안의 내용만 사용
- 모르면 "문서에서 확인할 수 없습니다"
- 출처(기관 + 파일명) 명시
- 의료 정보 면책 문구 포함

In [9]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

llm = ChatOpenAI(model=GEN_MODEL, temperature=0)

RAG_PROMPT = ChatPromptTemplate.from_template(
    """당신은 유방암 정보 검색 보조 시스템입니다.

아래 [참고 문서]만 사용해서 [질문]에 답변하세요. 문서에 없는 내용은 추측하지 말고 "제공된 문서에서 확인할 수 없습니다"라고 답하세요.
답변 마지막에는 반드시 다음 두 가지를 포함하세요:
1. 출처: 참고한 문서명과 페이지 (예: 출처: 국립암센터 유방암 검진 권고안, p.5)
2. 면책 문구: "이 답변은 일반 정보 제공 목적이며, 실제 진단·치료는 반드시 의료진과 상의하세요."

[참고 문서]
{context}

[질문]
{question}

[답변]"""
)


def format_context(docs):
    parts = []
    for i, d in enumerate(docs, 1):
        meta = d.metadata
        header = f"[{i}] 출처: {meta.get('org','?')} / {meta.get('title','?')} / p.{meta.get('page','?')}"
        parts.append(f"{header}\n{d.page_content}")
    return "\n\n---\n\n".join(parts)


def ask(question: str):
    docs = retriever.invoke(question)
    prompt = RAG_PROMPT.format(context=format_context(docs), question=question)
    answer = (llm | StrOutputParser()).invoke(prompt)
    return {
        "question": question,
        "answer": answer,
        "contexts": [d.page_content for d in docs],
        "retrieved_docs": docs,
    }

In [10]:
result = ask(test_q)
print(result["answer"])

유방암 검진은 40세 이상의 여성에게 권장되며, 국가암검진 프로그램에서는 2년마다 유방촬영검사를 실시하고 있습니다.

출처: 국립암센터 / 국민 암예방 수칙 실천지침 - 유방암, p.8
면책 문구: "이 답변은 일반 정보 제공 목적이며, 실제 진단·치료는 반드시 의료진과 상의하세요."

---
## 6. 평가용 질문 세트 (Golden Set v0)

5~10개 질문을 도메인 기준으로 작성. 4주차에서 확장할 거니까 일단 baseline 측정용.

- `ground_truth`는 RAGAS 일부 지표(Context Recall 등)에 쓰이는데, 3주차에서는 Faithfulness / Answer Relevancy / Context Precision만 측정할 거라 비워둬도 됨. 단, 4주차 이후를 위해 가능한 만큼 채워두면 좋다.

In [11]:
import pandas as pd

golden = [
    {
        "question": "유방암 검진은 몇 살부터 받는 것이 권장되나요?",
        "ground_truth": "국립암센터 권고안은 만 40세 이상 여성에게 2년마다 유방촬영술 검진을 권고합니다.",
    },
    {
        "question": "유방암의 주요 위험 요인은 무엇인가요?",
        "ground_truth": "고연령, 가족력, BRCA1/2 등 유전적 요인, 이른 초경/늦은 폐경, 호르몬 노출, 비만 등이 알려져 있습니다.",
    },
    {
        "question": "HER2 양성 유방암이란 무엇인가요?",
        "ground_truth": "HER2 단백이 과발현된 유방암으로, 표적치료제(트라스투주맙 등)가 효과적입니다.",
    },
    {
        "question": "유방암 1기와 2기의 차이는 무엇인가요?",
        "ground_truth": "종양 크기와 림프절 전이 여부에 따라 병기가 나뉘며, 1기는 종양이 작고 림프절 전이 없음, 2기는 종양이 크거나 일부 림프절 전이가 있는 상태입니다.",
    },
    {
        "question": "DCIS(상피내암)는 침윤성 유방암과 어떻게 다른가요?",
        "ground_truth": "DCIS는 유관 내에 머무르는 0기 암이며, 침윤성 유방암은 기저막을 뚫고 주변 조직으로 침범한 상태입니다.",
    },
    {
        "question": "항호르몬제 치료는 어떤 환자에게 사용되나요?",
        "ground_truth": "호르몬 수용체 양성(ER+/PR+) 유방암 환자에게 사용되며, 타목시펜이나 아로마타제 억제제가 대표적입니다.",
    },
    {
        "question": "유방절제술 후 재건수술은 어떤 옵션이 있나요?",
        "ground_truth": "보형물 재건, 자가조직 재건(복부/등 피판 등), 또는 두 방식의 조합이 있습니다.",
    },
    {
        "question": "BRCA 유전자 검사는 누구에게 권장되나요?",
        "ground_truth": "가족 중 유방암·난소암 환자가 있거나, 젊은 나이에 발병한 경우 등 유전성 위험이 의심될 때 권장됩니다.",
    },
    {
        "question": "전이성 유방암(4기)의 일반적인 치료 목표는 무엇인가요?",
        "ground_truth": "완치보다는 증상 완화와 생존 연장, 삶의 질 유지가 주된 목표입니다.",
    },
    {
        "question": "유방암 환자가 식이요법에서 주의할 점은?",
        "ground_truth": "균형 잡힌 식단, 적정 체중 유지, 음주 제한이 권장되며 특정 식품의 효과는 근거가 제한적입니다.",
    },
]

df_golden = pd.DataFrame(golden)
golden_path = DATA_EVAL / "golden_set_v0.csv"
df_golden.to_csv(golden_path, index=False, encoding="utf-8-sig")
print(f"저장: {golden_path}")
df_golden

저장: /Users/jian/Documents/rag-agent-portfolio/data/eval/golden_set_v0.csv

,question,ground_truth
0,유방암 검진은 몇 살부터 받는 것이 권장되나요?,국립암센터 권고안은 만 40세 이상 여성에게 2년마다 유방촬영술 검진을 권고합니다.
1,유방암의 주요 위험 요인은 무엇인가요?,"고연령, 가족력, BRCA1/2 등 유전적 요인, 이른 초경/늦은 폐경, 호르몬 노..."
2,HER2 양성 유방암이란 무엇인가요?,"HER2 단백이 과발현된 유방암으로, 표적치료제(트라스투주맙 등)가 효과적입니다."
3,유방암 1기와 2기의 차이는 무엇인가요?,"종양 크기와 림프절 전이 여부에 따라 병기가 나뉘며, 1기는 종양이 작고 림프절 전..."
4,DCIS(상피내암)는 침윤성 유방암과 어떻게 다른가요?,"DCIS는 유관 내에 머무르는 0기 암이며, 침윤성 유방암은 기저막을 뚫고 주변 조..."
5,항호르몬제 치료는 어떤 환자에게 사용되나요?,"호르몬 수용체 양성(ER+/PR+) 유방암 환자에게 사용되며, 타목시펜이나 아로마타..."
6,유방절제술 후 재건수술은 어떤 옵션이 있나요?,"보형물 재건, 자가조직 재건(복부/등 피판 등), 또는 두 방식의 조합이 있습니다."
7,BRCA 유전자 검사는 누구에게 권장되나요?,"가족 중 유방암·난소암 환자가 있거나, 젊은 나이에 발병한 경우 등 유전성 위험이 ..."
8,전이성 유방암(4기)의 일반적인 치료 목표는 무엇인가요?,"완치보다는 증상 완화와 생존 연장, 삶의 질 유지가 주된 목표입니다."
9,유방암 환자가 식이요법에서 주의할 점은?,"균형 잡힌 식단, 적정 체중 유지, 음주 제한이 권장되며 특정 식품의 효과는 근거가..."

---
## 7. 전체 질문에 대해 RAG 실행 → 결과 수집

gpt-4o-mini(API)로 10개 답변을 생성한다. API라 빠르게 끝난다(수십 초~1~2분).

In [12]:
from tqdm import tqdm

results = []
for q in tqdm(df_golden["question"].tolist(), desc="RAG"):
    r = ask(q)
    results.append(
        {
            "question": r["question"],
            "answer": r["answer"],
            "contexts": r["contexts"],
        }
    )

# ground_truth 결합
for r, g in zip(results, golden):
    r["ground_truth"] = g["ground_truth"]

df_results = pd.DataFrame(results)
df_results.to_json(
    DATA_PROCESSED / "week3_rag_results.json",
    orient="records",
    force_ascii=False,
    indent=2,
)
print("저장 완료")
df_results[["question", "answer"]]

RAG: 100%|██████████| 10/10 [00:35<00:00,  3.52s/it]

저장 완료

,question,answer
0,유방암 검진은 몇 살부터 받는 것이 권장되나요?,"유방암 검진은 40세부터 시작하는 것이 권장됩니다. 특히, 40-69세의 무증상 여..."
1,유방암의 주요 위험 요인은 무엇인가요?,유방암의 주요 위험 요인은 다음과 같습니다:\n\n1. 비만 (특히 폐경 후 여성)...
2,HER2 양성 유방암이란 무엇인가요?,"HER2 양성 유방암은 유방암의 한 유형으로, 종양 세포 표면에 비정상적으로 높은 ..."
3,유방암 1기와 2기의 차이는 무엇인가요?,유방암 1기와 2기의 차이는 주로 종양의 크기와 림프절 전이 여부에 있습니다. \n...
4,DCIS(상피내암)는 침윤성 유방암과 어떻게 다른가요?,"DCIS(상피내암)는 비침윤성 유방암의 한 형태로, 암세포가 유관 내에 존재하지만 ..."
5,항호르몬제 치료는 어떤 환자에게 사용되나요?,항호르몬제 치료는 호르몬 수용체 양성인 유방암 환자에게 사용됩니다. 이 치료는 성호...
6,유방절제술 후 재건수술은 어떤 옵션이 있나요?,유방절제술 후 재건수술에는 즉시 유방재건술과 지연 유방재건술 두 가지 옵션이 있습니...
7,BRCA 유전자 검사는 누구에게 권장되나요?,BRCA 유전자 검사는 다음과 같은 경우에 권장됩니다:\n\n1. BRCA1/2 유...
8,전이성 유방암(4기)의 일반적인 치료 목표는 무엇인가요?,전이성 유방암(4기)의 일반적인 치료 목표는 생존 기간을 연장하고 삶의 질을 향상시...
9,유방암 환자가 식이요법에서 주의할 점은?,"유방암 환자가 식이요법에서 주의할 점은 다음과 같습니다. 건강한 체중을 유지하고, ..."

---
## 8. RAGAS 평가

- **생성 LLM = gpt-4o-mini, 채점(judge) LLM = Claude**로 분리한다. 같은 모델이 답하고 채점하면 self-preference 편향이 생기므로 다른 계열을 쓴다.
- Jupyter(특히 Windows)에서 RAGAS가 내부 async와 충돌해 **모든 점수가 NaN**으로 나오는 경우가 있어, `nest_asyncio.apply()`로 먼저 보정한다.
- 임베딩은 answer_relevancy 계산에 쓰이며, 로컬 e5를 그대로 사용(무료).

In [13]:
import nest_asyncio
nest_asyncio.apply()  # Jupyter async 충돌 방지

from ragas import evaluate, EvaluationDataset
from ragas.metrics import faithfulness, answer_relevancy, context_precision
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_anthropic import ChatAnthropic

# 채점(judge) = Claude (생성 gpt-4o-mini와 다른 계열), 임베딩은 로컬 e5
ragas_llm = LangchainLLMWrapper(ChatAnthropic(model=JUDGE_MODEL, temperature=0))
ragas_emb = LangchainEmbeddingsWrapper(embeddings)

# ragas 0.2 스키마: user_input / response / retrieved_contexts / reference
# (옛 question/answer/contexts/ground_truth로 넣으면 reference가 전달 안 돼 context_precision이 0이 됨)
samples = [
    {
        "user_input": r["question"],
        "response": r["answer"],
        "retrieved_contexts": r["contexts"],
        "reference": r["ground_truth"],
    }
    for r in results
]
eval_dataset = EvaluationDataset.from_list(samples)

scores = evaluate(
    dataset=eval_dataset,
    metrics=[faithfulness, answer_relevancy, context_precision],
    llm=ragas_llm,
    embeddings=ragas_emb,
)
print(scores)

Evaluating:   0%|          | 0/30 [00:00<?, ?it/s]

Exception raised in Job[3]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Exception raised in Job[6]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)
Exception raised in Job[9]: LLMDidNotFinishException(The LLM generation was not completed. Please increase the max_tokens and try again.)

{'faithfulness': 0.6480, 'answer_relevancy': 0.8704, 'context_precision': 0.7428}

In [14]:
# 결과를 DataFrame으로 정리해 저장
df_scores = scores.to_pandas()
df_scores.to_csv(
    DATA_PROCESSED / "week3_ragas_scores.csv", index=False, encoding="utf-8-sig"
)

# 입력 필드가 아닌 수치 컬럼 = metric 컬럼 (버전에 따라 이름이 달라도 자동 인식)
_input_cols = {"user_input", "response", "retrieved_contexts", "reference",
               "question", "answer", "contexts", "ground_truth"}
metric_cols = [c for c in df_scores.columns
               if c not in _input_cols and df_scores[c].dtype.kind in "fi"]

print("--- Baseline 평균 점수 ---")
for col in metric_cols:
    print(f"  {col}: {df_scores[col].mean():.4f}")

df_scores

--- Baseline 평균 점수 ---
  faithfulness: 0.6480
  answer_relevancy: 0.8704
  context_precision: 0.7428

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_precision
0,유방암 검진은 몇 살부터 받는 것이 권장되나요?,[이 적어도 수년 전의 검진자료인 점을 고려한다면 70세 미만에 한정하는 연령제한은...,"유방암 검진은 40세부터 시작하는 것이 권장됩니다. 특히, 40-69세의 무증상 여...",국립암센터 권고안은 만 40세 이상 여성에게 2년마다 유방촬영술 검진을 권고합니다.,0.500000,0.832989,1.000000
1,유방암의 주요 위험 요인은 무엇인가요?,[국민 암예방 수칙 실천지침 _ 유방암\n4\n5\n유방암의 주요 위험요인으로는 비...,유방암의 주요 위험 요인은 다음과 같습니다:\n\n1. 비만 (특히 폐경 후 여성)...,"고연령, 가족력, BRCA1/2 등 유전적 요인, 이른 초경/늦은 폐경, 호르몬 노...",NaN,0.812759,1.000000
2,HER2 양성 유방암이란 무엇인가요?,[성장을 촉진하기 위해 추가되는 많은 수의 수용체 (ER 또는 PgR) 를 가지고 ...,"HER2 양성 유방암은 유방암의 한 유형으로, 종양 세포 표면에 비정상적으로 높은 ...","HER2 단백이 과발현된 유방암으로, 표적치료제(트라스투주맙 등)가 효과적입니다.",NaN,0.849265,0.750000
3,유방암 1기와 2기의 차이는 무엇인가요?,[2023 The 10\nth Korean Clinical Practice Guid...,유방암 1기와 2기의 차이는 주로 종양의 크기와 림프절 전이 여부에 있습니다. \n...,"종양 크기와 림프절 전이 여부에 따라 병기가 나뉘며, 1기는 종양이 작고 림프절 전...",NaN,0.827017,0.000000
4,DCIS(상피내암)는 침윤성 유방암과 어떻게 다른가요?,[7\n환자를 위한 ESMO 안내서\n유방암이란? \n유방암은 유방 조직에서 형성되...,"DCIS(상피내암)는 비침윤성 유방암의 한 형태로, 암세포가 유관 내에 존재하지만 ...","DCIS는 유관 내에 머무르는 0기 암이며, 침윤성 유방암은 기저막을 뚫고 주변 조...",0.666667,0.869159,0.833333
5,항호르몬제 치료는 어떤 환자에게 사용되나요?,[위와 같이 약을 늦게 복용하거나 복용을 거르는 경우는 기록하여 담당 의사에게 \n...,항호르몬제 치료는 호르몬 수용체 양성인 유방암 환자에게 사용됩니다. 이 치료는 성호...,"호르몬 수용체 양성(ER+/PR+) 유방암 환자에게 사용되며, 타목시펜이나 아로마타...",0.625000,0.948077,0.866667
6,유방절제술 후 재건수술은 어떤 옵션이 있나요?,"[고려할 수 있다(63, 64). 그러나 원칙적으로 수술 후 미용적 효과가 종양학적...",유방절제술 후 재건수술에는 즉시 유방재건술과 지연 유방재건술 두 가지 옵션이 있습니...,"보형물 재건, 자가조직 재건(복부/등 피판 등), 또는 두 방식의 조합이 있습니다.",0.555556,0.836510,0.500000
7,BRCA 유전자 검사는 누구에게 권장되나요?,[병하는 질환과 관련되어 있으므로 유전자검사의 장단점을 비교하고 스스로 결정할 수 ...,BRCA 유전자 검사는 다음과 같은 경우에 권장됩니다:\n\n1. BRCA1/2 유...,"가족 중 유방암·난소암 환자가 있거나, 젊은 나이에 발병한 경우 등 유전성 위험이 ...",0.700000,0.866800,0.477778
8,전이성 유방암(4기)의 일반적인 치료 목표는 무엇인가요?,[30\n유방암\n전이성 (IV 기) 유방암에 대한 치료 선택 사항으로는 \n무엇이...,전이성 유방암(4기)의 일반적인 치료 목표는 생존 기간을 연장하고 삶의 질을 향상시...,"완치보다는 증상 완화와 생존 연장, 삶의 질 유지가 주된 목표입니다.",0.600000,0.863286,1.000000
9,유방암 환자가 식이요법에서 주의할 점은?,[국민 암예방 수칙 실천지침 _ 유방암\n8\n9\n 유방암을\n예방할 수 있는 방...,"유방암 환자가 식이요법에서 주의할 점은 다음과 같습니다. 건강한 체중을 유지하고, ...","균형 잡힌 식단, 적정 체중 유지, 음주 제한이 권장되며 특정 식품의 효과는 근거가...",0.888889,0.997869,1.000000

---
## 9. 회고용 — 잘못 검색된 chunk 찾기

4주차 retrospective에서 "잘못 검색된 chunk 예시 2개 이상"이 필요하다.  
Context Precision이 낮은 질문 위주로 확인하면 좋다.

In [15]:
# context_precision 계열 컬럼 자동 탐지 (0.2에서 이름이 다를 수 있음)
prec_col = next((c for c in df_scores.columns if "precision" in c.lower()), None)
COL_Q = "user_input" if "user_input" in df_scores.columns else "question"
COL_A = "response" if "response" in df_scores.columns else "answer"
COL_C = "retrieved_contexts" if "retrieved_contexts" in df_scores.columns else "contexts"

if prec_col:
    worst = df_scores.nsmallest(3, prec_col)
    for idx, row in worst.iterrows():
        print("=" * 60)
        print(f"질문: {row[COL_Q]}")
        print(f"{prec_col}: {row[prec_col]:.3f}")
        print(f"\n답변: {str(row[COL_A])[:300]}...")
        print("\n검색된 chunk:")
        ctxs = row[COL_C] if isinstance(row[COL_C], (list, tuple)) else []
        for i, c in enumerate(ctxs, 1):
            print(f"  [{i}] {str(c)[:200].replace(chr(10), ' ')}...")
        print()
else:
    print("precision 계열 컬럼을 찾지 못함. 컬럼:", list(df_scores.columns))

============================================================
질문: 유방암 1기와 2기의 차이는 무엇인가요?
context_precision: 0.000

답변: 유방암 1기와 2기의 차이는 주로 종양의 크기와 림프절 전이 여부에 있습니다.

1기 유방암은 AJCC Cancer Staging Manual의 기준에 따라 T1N0M0에 해당하며, 종양이 2cm 이하이고 림프절로 전이되지 않은 상태입니다. 반면, 2기 유방암은 T2N0M0 또는 T1N1M0, T2N1M0에 해당하며, 종양이 2cm를 초과하거나 림프절로 전이된 경우를 포함합니다. 즉, 2기 유방암은 1기보다 더 진행된 상태로, 종양의 크기나 림프절 전이에 따라 구분됩니다.

출처: 대한유방암학회 / 제10차 한국유방암 진료권고안 ...

검색된 chunk:
  [1] 2023 The 10 th Korean Clinical Practice Guideline for Breast Cancer | 41 제2장 조기 유방암 제3장 재발 및 전이성 유방암 제4장 유전성 유방암  제1장 비침습 유방암 제1장 비침습 유방암: 관상피내암과 소엽상피내암 1.1. 관상피내암의 정의 관상피내암은 말단 유관 소엽 (terminal duct-l...
  [2] 2M0), IIIC기(anyTN3M0)에 해당한다. 국소진행성 유방암은 근치적 수술이 가능한 유방암(T3N1M0)과 근치적  수술이 어려운 유방암(N2-3 혹은T4)으로 나눌 수 있다. 근치적수술이 어려운 국소진행성 유방암의 경우 수술 전  항암요법이 필수적이다. 2.2. 조기 유방암의 진단 유방암의 진단을 위해 병력청취, 신체검사, 혈액검사, 흉부단순촬영...
  [3] 8 유방암 침윤성 유방암 침윤성 유방암은 유관 외부로 퍼진 암 (침습관암종) 또는 소엽 (침습소염암종) 을 가리키는  명칭입니다. 이들은 조직학에 따라 더 세부적으로 분류될 수 있습니다. 예를 들어, 세관암종,  점액암종, 수질암종, 유두모양암종 등은 더 드문 유방암의 아형들입니다. 유방암은 또한 질병의 진행 정도에 의해 분류됩니다: 초기 유방암 유방암은 ...
  [4] 2023 The 10 th Korean Clinical Practice Guideline for Breast Cancer | 59 제2장 조기 유방암 제3장 재발 및 전이성 유방암 제4장 유전성 유방암  제1장 비침습 유방암 제2장 조기 유방암 2.1. 조기 유방암의 정의 AJCC Cancer Staging Manual 8 th edition (2017)의...
  [5] 4 유방암 유방암: 주요 정보 요약 유방암에 대한 설명 •	 유방암은 유방의 세포에서 발생하는 것으로 세포가 비정상적으로 성장 및 증식하여 응어리 또는  종양을 형성하는 질환입니다. •	 유방암의 초기 단계는 비침윤성 질환 (0 기) 으로, 유방의 관 또는 소엽 내에 존재하며 건강한 유방  조직으로 전이되지 않습니다 (제자리 암종이라고도 함). 침윤성 유방...

============================================================
질문: BRCA 유전자 검사는 누구에게 권장되나요?
context_precision: 0.478

답변: BRCA 유전자 검사는 다음과 같은 경우에 권장됩니다:

1. BRCA1/2 유전자 변이가 확인된 가계의 환자와 가족.
2. 가계 내 BRCA1/2 유전자검사를 시행한 구성원이 없는 경우, 본인이 유방암 환자이며 3등친 이내에 유방암과 난소암 가족력이 있는 경우.
3. 발병 나이와 관계없이 본인을 포함한 유방암 가족력이 3명 이상인 경우.

또한, BRCA1/2 유전자 변이를 보유할 가능성이 높은 고위험군에 대해서는 유전상담과 유전자검사가 필요합니다. 검사대상자는 만 19세 이상의 성인으로, 충분한 설명 후 자율적인 검사의 결정과 ...

검색된 chunk:
  [1] 병하는 질환과 관련되어 있으므로 유전자검사의 장단점을 비교하고 스스로 결정할 수 있는 만 19세 이상의 성인 에게 시행한다[82,83] (LE 3, GR A). 특히, 생명윤리법 제50조, 생명윤리법 시행령 제20조에 의해 BRCA1/2 유 전자는 진료를 담당하는 의사가 해당 질환의 고위험군에 속한다고 판단하거나 해당 질환에 확실하게 진단된 사람 을 대상으...
  [2] 2023 The 10 th Korean Clinical Practice Guideline for Breast Cancer | 185 제2장 조기 유방암 제3장 재발 및 전이성 유방암 제4장 유전성 유방암  제1장 비침습 유방암 하다[85] (LE 3, GR A).  누구든지 유전정보를 이유로 교육·고용·승진·보험 등에 사회활동에서 차별을 받지 못하며 타인에...
  [3] 별 임상 환경에 따라 달리 반영할 수 있다.  BRCA1/2 유전자 변이가 확인된 가계의 환자와 가족은 우선적으로 해당 변이에 대한 BRCA 유전자검사의 대상이 된다.  가계 내 BRCA1/2 유전자검사를 시행한 구성원이 없는 경우는 본인이 유방암 환자이며 3등친 이내에 유방암과 난 소암 가족력이 있는 경우 검사가 권고된다. 특히, 발병 나이와 관계없이 본...
  [4] 있다.  4 C [51] 4.4.2. 검사대상 BRCA1/2 유전자 변이를 보유할 가능성이 높은 고위험군에 대해서는 유전상담과 유전자검사가 필요하다. 동시 에 다중유전자패널 검사의 시행이 확대됨에 따라 BRCA1/2 유전자와 침투도가 높은 다른 유전자(특히, CDH1,  PALB2, PTEN, TP53)를 함께 고려하여 유전성 유방암 고위험군이 누락되지 않...
  [5] 에 다중유전자패널 검사를 고려한다(LE 3, GR B).  현재 난소암, 난관암, 복막암에서는 점액성 조직형을 제외한 모든 조직형에서 BRCA 유전자검사가 권고되므로,  BRCA 위험도 예측과 무관하게 검사의 적응증이 된다. 혈액 검체로 유전성 유전자검사가 급여로 시행할 수 있고,  종양조직에서 차세대염기서열분석(NGS)이나 상동재조합결핍(HRD)검사를 시...

============================================================
질문: 유방절제술 후 재건수술은 어떤 옵션이 있나요?
context_precision: 0.500

답변: 유방절제술 후 재건수술에는 즉시 유방재건술과 지연 유방재건술 두 가지 옵션이 있습니다. 즉시 유방재건술은 유방전절제술 후 방사선요법이 필요하지 않은 경우 가장 좋은 미용적 결과를 보입니다. 반면, 수술 후 방사선요법이 필요한 경우에는 자가조직을 이용한 지연 유방재건술이 선호됩니다. 또한, 조직확장 보형물 삽입을 이용한 유방재건수술은 보형물을 덮을 만한 충분한 양의 조직이 있어야 가능하며, 여러 조건에 따라 적합성이 달라질 수 있습니다.

출처: 대한유방암학회 / 제10차 한국유방암 진료권고안 (2023) / p.63, p.62
...

검색된 chunk:
  [1] 고려할 수 있다(63, 64). 그러나 원칙적으로 수술 후 미용적 효과가 종양학적 안전보다 우선시될 수 없으 며, 따라서 치료 결정에 영향을 미쳐서는 안된다(65-67). 유방전절제술을 받는 환자 중 유방암의 유전적 소인이 있는 환자에서 동측 유방의 재발위험 및 반대편 유 방암의 발생위험을 감소시키기 위해 예방적 양측 유방절제술을 고려할 수 있다. 이 경우...
  [2] 법이 필요치 않은 경우 즉시 유방재건술이 가장 좋은 미용적 결과를 보이지만 수술 후 방사선요법이 필 요한 경우에는 자가조직을 이용한 지연 유방재건술이 선호된다(68, 69) (LE 3, GR B). 조직확장 보형물 (expander-implant) 삽입을 이용한 유방재건수술은 보형물을 덮을 만한 충분한 양의 조직이 있어야 가 능하며, 양측 혹은 예방적 유방...
  [3] 예후가 좋은 일부 선택된 환자군에서 유방보존술 후 근접 방사선치료나 외부  방사선치료를 이용한 가속 부분유방 방사선치료를 고려할 수 있다. 1 A [139-143] 70세 이상, 종양크기 3cm 이하, 림프절 음성，ER 양성이고 절제연 음성인  환자에서는 유방보존술을 시행한 후에도 방사선치료를 시행하지 않고 타목 시펜 또는 아로마타제억제제 등의 내분비치료 ...
  [4] 대한 근거는 부족하다[102,211,218,219]. 2018년 개정한 코크란 리뷰에서는 26개의 연구에서 위험감소 반대 쪽 유방절제술이 반대편 유방암 발생률의 위험을 낮추지만, 생존이득에 대해서는 결론에 일관성이 없으며, 생존 이득이 명확하게 보였던 7개 연구에서도 위험감소 난소난관절제술의 효과를 보정하였을 때는 생존이득이 상쇄 되는 결과가 보였다는 기존...
  [5] 세포가 병리적으로 확인된 경우 음성 절제연을 확보하기 위해 일반적으로 추가절제나 전절제술로의 전환 이 필요하다(52). 유방보존술 후 whole breast radiation 예정인 환자의 경우 더 넓은 절제연의 확보는  국소재발에 의미 있는 영향을 주지 못하며(53), 절제연의 침범이 국소적인 경우(focally positive) 중 EIC 가 없는 경우...